---
image: gradle:6.7.0-jdk11

stages:
  - build
  - deploy

before_script:
  - apt-get update
  - chmod +x ./gradlew

build job:
  tags:
    - runner
  stage: build
  artifacts:
    paths:
      - build/libs
  script:
    - ./gradlew bootjar
    - scp -o StricthostKeyChecking=no {Dockerfile, docker-compose.yml, build/libs/dotaStats-0.0.1-SNAPSHOT.jar} prod-user@prod.internal:~/deployment/

deploy job:
  tags:
    - runner
  stage: deploy
  script:
    - ssh -o StricthostKeyChecking=no prod-user@prod.internal "cd deployment/ && sudo docker-compose up -d --build"
