---
image: gradle:6.7.0-jdk11

stages:
  - test
  - build
  - deploy

before_script:
  - apt-get update
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - chmod +x ./gradlew

test job:
  stage: test
  tags:
    - runner
  script:
    - ./gradlew clean test

build job:
  tags:
    - runner
  stage: build
  artifacts:
    paths:
      - build/libs
  script:
    - ./gradlew bootjar
    - scp -o StricthostKeyChecking=no {Dockerfile,docker-compose.yml,dotastats.service,build/libs/dotaStats-0.0.1-SNAPSHOT.jar} prod-user@192.168.0.2:~/deployment/
    - scp -o StricthostKeyChecking=no nginx/reverse-proxy.conf prod-user@192.168.0.2:~/deployment/nginx/

deploy job:
  tags:
    - runner
  stage: deploy
  script:
    - ssh -o StricthostKeyChecking=no prod-user@192.168.0.2 "cd deployment/ && [[ -f /etc/systemd/system/dotastats.service ]] || sudo cp dotastats.service /etc/systemd/system/ && sudo service dotastats restart"
